document.querySelector('link[rel="stylesheet"]').href = 'messagerie.css/messagerie.css';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from './auth-config.js';
const sb = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
const $ = (id) => document.getElementById(id);
const status = $('status'), messenger = $('messenger'), list = $('conversation-list'), results = $('search-results');
let user = null, current = null, people = new Map(), channel = null, timer = null;
const allowed = new Set(['image/jpeg','image/png','image/webp','image/gif','video/mp4','video/webm','video/quicktime','audio/mpeg','audio/mp4','audio/wav','audio/ogg','audio/webm','application/pdf']);
function notice(message, error = false) { status.textContent = message; status.classList.toggle('error', error); status.classList.remove('hidden'); }
function node(tag, cls, text) { const e = document.createElement(tag); if (cls) e.className = cls; if (text !== undefined) e.textContent = text; return e; }
function avatar(name, url) { if (url) { const i = node('img','avatar'); i.src = url; i.alt = ''; return i; } return node('span','avatar',(name || '?').trim().slice(0,1).toUpperCase()); }
function row(person, preview = '', id = '') { const b = node('button','person-row' + (current === id ? ' active' : '')); b.type = 'button'; b.append(avatar(person.display_name,person.avatar_url)); const copy = node('span','person-copy'); copy.append(node('strong','',person.display_name || 'Membre'),node('small','',preview)); b.append(copy); b.addEventListener('click',() => id ? openConversation(id,person) : startChat(person.id)); return b; }
async function searchProfiles(q) { results.replaceChildren(); if (!user || q.trim().length < 2) return; const term = q.trim().replace(/[,%]/g,''); const {data,error} = await sb.from('profiles').select('id,display_name,avatar_url').ilike('display_name','%' + term + '%').neq('id',user.id).limit(10); if (error) { results.append(node('p','empty-list','Recherche indisponible. Réessayez dans un instant.')); return; } if (!data?.length) { results.append(node('p','empty-list','Aucun profil trouvé.')); return; } for (const p of data) { people.set(p.id,p); const item = row(p,'Voir le profil'); item.setAttribute('aria-label','Ouvrir le profil de ' + (p.display_name || 'Membre')); item.addEventListener('click',event => { event.stopImmediatePropagation(); location.href = 'profil.html?id=' + encodeURIComponent(p.id); },true); results.append(item); } }
async function startChat(target) { if (!user || !target || target === user.id) return; notice('Ouverture de la conversation…'); try { let person = people.get(target); if (!person) { const {data,error} = await sb.from('profiles').select('id,display_name,avatar_url').eq('id',target).maybeSingle(); if (error) throw error; person = data || {id:target,display_name:'Membre'}; people.set(target,person); } const {data,error} = await sb.rpc('start_direct_conversation',{p_target_user:target}); if (error) throw error; const id = typeof data === 'string' ? data : data?.conversation_id || data?.id; if (!id) throw new Error('Supabase n’a pas renvoyé l’identifiant de la conversation.'); await openConversation(id,person); } catch (error) { notice('Impossible d’ouvrir la conversation : ' + (error?.message || 'erreur Supabase'),true); } }
async function refreshList() { if (!user) return; const {data:ownRows,error} = await sb.from('conversation_participants').select('conversation_id,user_id').eq('user_id',user.id); if (error) { notice('Impossible de charger les conversations : ' + error.message,true); return; } const ids = [...new Set((ownRows || []).map(x => x.conversation_id))]; if (!ids.length) { list.replaceChildren(node('p','empty-list','Vos conversations apparaîtront ici.')); return; } const {data:members,error:participantError} = await sb.from('conversation_participants').select('conversation_id,user_id').in('conversation_id',ids); if (participantError) { notice('Impossible de charger les participants : ' + participantError.message,true); return; } const others = [...new Set((members || []).map(x => x.user_id).filter(id => id !== user.id))]; const [profiles,convos,msgs] = await Promise.all([others.length ? sb.from('profiles').select('id,display_name,avatar_url').in('id',others) : Promise.resolve({data:[],error:null}),sb.from('conversations').select('id,last_message_at').in('id',ids).order('last_message_at',{ascending:false}),sb.from('messages').select('conversation_id,body,media_name,created_at').in('conversation_id',ids).order('created_at',{ascending:false}).limit(ids.length * 3)]); const failure = profiles.error || convos.error || msgs.error; if (failure) { notice('Impossible de synchroniser les conversations : ' + failure.message,true); return; } (profiles.data || []).forEach(p => people.set(p.id,p)); list.replaceChildren(); for (const c of convos.data || []) { const other = (members || []).find(x => x.conversation_id === c.id && x.user_id !== user.id); if (!other) continue; const p = people.get(other.user_id) || {id:other.user_id,display_name:'Membre'}; const latest = (msgs.data || []).find(x => x.conversation_id === c.id); list.append(row(p,latest?.body || latest?.media_name || 'Nouvelle conversation',c.id)); } if (!list.childElementCount) list.append(node('p','empty-list','Vos conversations apparaîtront ici.')); }
async function signed(path) { const {data,error} = await sb.storage.from('private-messages').createSignedUrl(path,3600); return error ? null : data?.signedUrl || null; }
async function renderMessages() { if (!current) return; const {data,error} = await sb.from('messages').select('id,conversation_id,sender_id,body,media_path,media_name,media_type,created_at').eq('conversation_id',current).order('created_at',{ascending:true}).limit(100); if (error) { notice('Impossible de charger les messages : ' + error.message,true); return; } const box = $('messages-list'); box.replaceChildren(); for (const m of data || []) { const item = node('article','message' + (m.sender_id === user.id ? ' mine' : '')); const bubble = node('div','message-bubble'); if (m.body) bubble.append(node('div','',m.body)); if (m.media_path) { const url = await signed(m.media_path); if (url) { let media; if (m.media_type?.startsWith('image/')) { media = node('img'); media.src = url; media.alt = m.media_name || 'Image reçue'; } else if (m.media_type?.startsWith('video/')) { media = node('video'); media.src = url; media.controls = true; } else if (m.media_type?.startsWith('audio/')) { media = node('audio'); media.src = url; media.controls = true; } else { media = node('a','',m.media_name || 'Ouvrir le fichier'); media.href = url; media.target = '_blank'; media.rel = 'noopener'; } bubble.append(media); } } item.append(bubble,node('time','',new Date(m.created_at).toLocaleString('fr-FR',{dateStyle:'short',timeStyle:'short'}))); box.append(item); } box.scrollTop = box.scrollHeight; }
async function openConversation(id,person) { current = id; $('chat-title').textContent = person.display_name || 'Conversation'; $('chat-placeholder').classList.add('hidden'); $('active-chat').classList.remove('hidden'); messenger.classList.add('chat-open'); await renderMessages(); if (channel) await sb.removeChannel(channel); channel = sb.channel('conversation-' + id).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:'conversation_id=eq.' + id},() => { renderMessages(); refreshList(); }).subscribe(); await refreshList(); status.classList.add('hidden'); }
$('profile-search').addEventListener('input',e => { clearTimeout(timer); timer = setTimeout(() => searchProfiles(e.target.value),250); });
$('media-file').addEventListener('change',e => { $('attachment-name').textContent = e.target.files[0]?.name || ''; });
$('back-to-list').addEventListener('click',() => messenger.classList.remove('chat-open'));
$('message-form').addEventListener('submit',async e => { e.preventDefault(); if (!current || !user) return; const body = $('message-body').value.trim(), file = $('media-file').files[0]; if (!body && !file) return; if (body.length > 1000) { notice('Votre message dépasse la limite de 1 000 caractères.',true); return; } if (file && (!allowed.has(file.type) || file.size > 15728640)) { notice('Choisissez une image, vidéo, audio ou PDF de 15 Mo maximum.',true); return; } const send = $('.send-button'); send.disabled = true; notice('Envoi du message…'); try { let media = {media_path:null,media_name:null,media_type:null,media_size:null}; if (file) { const safe = file.name.normalize('NFKD').replace(/[^a-zA-Z0-9._-]/g,'_').slice(-100); const path = current + '/' + user.id + '/' + Date.now() + '-' + crypto.randomUUID() + '-' + safe; const {error:uploadError} = await sb.storage.from('private-messages').upload(path,file,{contentType:file.type,upsert:false}); if (uploadError) throw uploadError; media = {media_path:path,media_name:file.name,media_type:file.type,media_size:file.size}; } const {error:insertError} = await sb.from('messages').insert({conversation_id:current,sender_id:user.id,body,...media}); if (insertError) throw insertError; $('message-body').value = ''; $('media-file').value = ''; $('attachment-name').textContent = ''; notice('Message envoyé et enregistré.'); await renderMessages(); await refreshList(); } catch (error) { notice('Message non envoyé : ' + (error?.message || 'erreur Supabase'),true); } finally { send.disabled = false; } });
const {data:{session}} = await sb.auth.getSession(); if (!session) { status.classList.add('hidden'); $('auth-required').classList.remove('hidden'); } else { user = session.user; messenger.classList.remove('hidden'); status.classList.add('hidden'); await refreshList(); const to = new URLSearchParams(location.search).get('to'); if (to && to !== user.id) await startChat(to); }
sb.auth.onAuthStateChange((_event,session) => { if (!session) location.href = 'connexion.html'; });
