document.querySelector('link[rel="stylesheet"]').href='messagerie.css/messagerie.css';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from './auth-config.js';const sb=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const $=id=>document.getElementById(id);
const status=$('status'), messenger=$('messenger'), list=$('conversation-list'), results=$('search-results');
let user=null, current=null, people=new Map(), channel=null, timer=null;
const allowed=new Set(['image/jpeg','image/png','image/webp','image/gif','video/mp4','video/webm','video/quicktime','audio/mpeg','audio/mp4','audio/wav','audio/ogg','audio/webm','application/pdf']);
function notice(message,error=false){status.textContent=message;status.classList.toggle('error',error);status.classList.remove('hidden')}
function node(tag,cls,text){const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e}
function avatar(name,url){if(url){const i=node('img','avatar');i.src=url;i.alt='';return i}return node('span','avatar',(name||'?').trim().slice(0,1).toUpperCase())}
function row(person,preview='',id=''){const b=node('button','person-row'+(current===id?' active':''));b.type='button';b.append(avatar(person.display_name,person.avatar_url));const copy=node('span','person-copy');copy.append(node('strong','',person.display_name||'Membre'),node('small','',preview));b.append(copy);b.addEventListener('click',()=>id?openConversation(id,person):startChat(person.id));return b}
async function searchProfiles(q){results.replaceChildren();if(q.trim().length<2)return;const {data,error}=await sb.from('profiles').select('id,display_name,avatar_url').ilike('display_name',`%${q.trim().replace(/[,%]/g,'')}%`).neq('id',user.id).limit(10);if(error){results.append(node('p','empty-list','Recherche indisponible.'));return}if(!data.length){results.append(node('p','empty-list','Aucun profil trouvé.'));return}for(const p of data){people.set(p.id,p);const item=row(p,'Voir le profil');item.setAttribute('aria-label',`Ouvrir le profil de ${p.display_name||'Membre'}`);item.addEventListener('click',event=>{event.stopImmediatePropagation();location.href=`profil.html?id=${encodeURIComponent(p.id)}`},true);results.append(item)}}
async function startChat(target){notice('Ouverture de la conversation…');const {data,error}=await sb.rpc('start_direct_conversation',{p_target_user:target});if(error){notice('La messagerie doit être activée sur le serveur. Réessayez après la configuration.',true);return}const id=typeof data==='string'?data:data?.conversation_id||data?.id;if(!id){notice('Impossible d’ouvrir cette conversation.',true);return}const p=people.get(target)||{id:target,display_name:'Conversation'};people.set(target,p);await refreshList();await openConversation(id,p)}
async function refreshList(){const {data:members,error}=await sb.from('conversation_participants').select('conversation_id,user_id').eq('user_id',user.id);if(error){notice('Impossible de charger les conversations. Vérifiez la configuration Supabase.',true);return}if(!members.length){list.replaceChildren(node('p','empty-list','Vos conversations apparaîtront ici.'));return}const ids=[...new Set(members.map(x=>x.conversation_id))];const others=[...new Set(members.map(x=>x.user_id).filter(x=>x!==user.id))];const [{data:profiles},{data:convos},{data:msgs}]=await Promise.all([sb.from('profiles').select('id,display_name,avatar_url').in('id',others),sb.from('conversations').select('id,last_message_at').in('id',ids).order('last_message_at',{ascending:false}),sb.from('messages').select('conversation_id,body,media_name,created_at').in('conversation_id',ids).order('created_at',{ascending:false}).limit(ids.length*3)]);(profiles||[]).forEach(p=>people.set(p.id,p));list.replaceChildren();for(const c of convos||[]){const m=members.find(x=>x.conversation_id===c.id&&x.user_id!==user.id);if(!m)continue;const p=people.get(m.user_id)||{id:m.user_id,display_name:'Membre'};const last=(msgs||[]).find(x=>x.conversation_id===c.id);list.append(row(p,last?.body||last?.media_name||'Nouvelle conversation',c.id))}if(!list.childElementCount)list.append(node('p','empty-list','Vos conversations apparaîtront ici.'))}
async function signed(path){const {data}=await sb.storage.from('private-messages').createSignedUrl(path,3600);return data?.signedUrl}
async function renderMessages(){if(!current)return;const {data,error}=await sb.from('messages').select('id,conversation_id,sender_id,body,media_path,media_name,media_type,created_at').eq('conversation_id',current).order('created_at',{ascending:true}).limit(100);if(error){notice('Impossible de lire ces messages.',true);return}const box=$('messages-list');box.replaceChildren();for(const m of data||[]){const item=node('article','message'+(m.sender_id===user.id?' mine':''));const bubble=node('div','message-bubble');if(m.body)bubble.append(node('div','',m.body));if(m.media_path){const url=await signed(m.media_path);if(url){let media;if(m.media_type?.startsWith('image/')){media=node('img');media.src=url;media.alt=m.media_name||'Image reçue'}else if(m.media_type?.startsWith('video/')){media=node('video');media.src=url;media.controls=true}else if(m.media_type?.startsWith('audio/')){media=node('audio');media.src=url;media.controls=true}else{media=node('a','',m.media_name||'Ouvrir le fichier');media.href=url;media.target='_blank';media.rel='noopener'}bubble.append(media)}}item.append(bubble,node('time','',new Date(m.created_at).toLocaleString('fr-FR',{dateStyle:'short',timeStyle:'short'})));box.append(item)}box.scrollTop=box.scrollHeight}
async function openConversation(id,person){current=id;$('chat-title').textContent=person.display_name||'Conversation';$('chat-placeholder').classList.add('hidden');$('active-chat').classList.remove('hidden');messenger.classList.add('chat-open');await renderMessages();if(channel)await sb.removeChannel(channel);channel=sb.channel('conversation-'+id).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:'conversation_id=eq.'+id},()=>{renderMessages();refreshList()}).subscribe();await refreshList()}
$('profile-search').addEventListener('input',e=>{clearTimeout(timer);timer=setTimeout(()=>searchProfiles(e.target.value),250)});$('media-file').addEventListener('change',e=>{$('attachment-name').textContent=e.target.files[0]?.name||''});$('back-to-list').addEventListener('click',()=>messenger.classList.remove('chat-open'));
$('message-form').addEventListener('submit',async e=>{e.preventDefault();if(!current)return;const body=$('message-body').value.trim(),file=$('media-file').files[0];if(!body&&!file)return;if(file&&(!allowed.has(file.type)||file.size>15728640)){notice('Choisissez une image, vidéo, audio ou PDF de 15 Mo maximum.',true);return}const send=$('.send-button');send.disabled=true;notice('Envoi…');let media={media_path:null,media_name:null,media_type:null,media_size:null};if(file){const safe=file.name.normalize('NFKD').replace(/[^a-zA-Z0-9._-]/g,'_').slice(-100);const path=`${current}/${user.id}/${Date.now()}-${crypto.randomUUID()}-${safe}`;const {error}=await sb.storage.from('private-messages').upload(path,file,{contentType:file.type,upsert:false});if(error){send.disabled=false;notice('Envoi du média impossible : '+error.message,true);return}media={media_path:path,media_name:file.name,media_type:file.type,media_size:file.size}}const {error}=await sb.from('messages').insert({conversation_id:current,sender_id:user.id,body,...media});send.disabled=false;if(error){notice('Message non envoyé : '+error.message,true);return}$('message-body').value='';$('media-file').value='';$('attachment-name').textContent='';notice('Message envoyé.');await renderMessages();await refreshList()});
const {data:{session}}=await sb.auth.getSession();if(!session){status.classList.add('hidden');$('auth-required').classList.remove('hidden')}else{user=session.user;messenger.classList.remove('hidden');status.classList.add('hidden');await refreshList();const params=new URLSearchParams(location.search);const to=params.get('to');if(to&&to!==user.id)await startChat(to)}
sb.auth.onAuthStateChange((_event,session)=>{if(!session)location.href='connexion.html'});
